### ISSUE TITLE
ERROR at build time : Multiple candidate to satisfy project requirements 

### ISSUE THREAD

**Issue by juan4java** [ks0777/zigbee-lamp#1]
**ESP IDF Version**
5.1.1
**Operating System**
Windows 10

**Condition**
I have clone the project, and cant build it, because the "led strip" component is ambiguos for the builder.
**Expected condition**
Build and run it in my ESP32C6 to use with a zigbee lamp.

**Detail about the error**
Every time who I tried to build the project the console otput is the same:
 
```
 ERROR: Cannot process component requirements.  Multiple candidates to satisfy project requirements:

 requirement: "led_strip" candidates: "espressif__led_strip, led_strip"
```

I checked the _**idf_component.yml**_ file , and his content is:
```
  ## IDF Component Manager Manifest File dependencies:
  espressif/esp-zboss-lib: "1.0.2"
  espressif/esp-zigbee-lib: "1.0.2"
  espressif/led_strip: "~2.3.0"
   ## Required IDF version
   idf:
     version: ">=5.0.0"
```

and the CMakeList.txt file  at project level is:

```
  # The following lines of boilerplate have to be in your project's CMakeLists
  # in this exact order for cmake to work correctly
  cmake_minimum_required(VERSION 3.16)
  include($ENV{IDF_PATH}/tools/cmake/project.cmake)
  project(zigbee-lamp)
```

I had see other similars errors online like [this](https://github.com/espressif/idf-component-manager/issues/25) but mi conditions aparently are well defined.

Also visited the espressif Build pages [here](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html), and still cant find where is the problem.

Last, I tried another option via deleted the "led strip" dependency, the compiler runs fine (it don't said nothing about the ambiguos dependency) , but finally it throws a lot of errors because the component don't exist and also because it is the expected behaivor.
